-- 更新完整的国家挖矿配置表数据
-- 包含全球200+个国家和地区的挖矿速率配置

USE bitcoin_mining_master;

-- 批量插入/更新所有国家配置数据
INSERT INTO country_mining_config (country_code, country_name, country_name_cn, mining_multiplier, is_active)
VALUES
  -- 26倍速率国家
  ('AU', 'Australia', '澳大利亚', 26, TRUE),
  ('US', 'United States', '美国', 26, TRUE),
  ('CA', 'Canada', '加拿大', 26, TRUE),
  
  -- 18倍速率国家
  ('NZ', 'New Zealand', '新西兰', 18, TRUE),
  ('DK', 'Denmark', '丹麦', 18, TRUE),
  ('CH', 'Switzerland', '瑞士', 18, TRUE),
  ('DE', 'Germany', '德国', 18, TRUE),
  ('UK', 'United Kingdom', '英国', 18, TRUE),
  ('AT', 'Austria', '奥地利', 18, TRUE),
  ('BE', 'Belgium', '比利时', 18, TRUE),
  ('FR', 'France', '法国', 18, TRUE),
  
  -- 15倍速率国家
  ('IS', 'Iceland', '冰岛', 15, TRUE),
  ('JP', 'Japan', '日本', 15, TRUE),
  ('LU', 'Luxembourg', '卢森堡', 15, TRUE),
  ('IL', 'Israel', '以色列', 15, TRUE),
  ('ES', 'Spain', '西班牙', 15, TRUE),
  ('EE', 'Estonia', '爱沙尼亚', 15, TRUE),
  ('SE', 'Sweden', '瑞典', 15, TRUE),
  ('IT', 'Italy', '意大利', 15, TRUE),
  ('MX', 'Mexico', '墨西哥', 15, TRUE),
  ('NL', 'Netherlands', '荷兰', 15, TRUE),
  ('CZ', 'Czech Republic', '捷克共和国', 15, TRUE),
  ('PL', 'Poland', '波兰', 15, TRUE),
  ('TW', 'Taiwan', '中国台湾', 15, TRUE),
  ('NO', 'Norway', '挪威', 15, TRUE),
  ('AE', 'United Arab Emirates', '阿拉伯联合酋长国', 15, TRUE),
  
  -- 10倍速率国家
  ('PR', 'Puerto Rico', '波多黎各', 10, TRUE),
  ('DM', 'Dominica', '多米尼克', 10, TRUE),
  ('LV', 'Latvia', '拉脱维亚', 10, TRUE),
  ('SI', 'Slovenia', '斯洛文尼亚', 10, TRUE),
  ('HR', 'Croatia', '克罗地亚', 10, TRUE),
  ('IE', 'Ireland', '爱尔兰', 10, TRUE),
  ('KG', 'Kyrgyzstan', '吉尔吉斯斯坦', 10, TRUE),
  ('LT', 'Lithuania', '立陶宛', 10, TRUE),
  ('CL', 'Chile', '智利', 10, TRUE),
  ('MU', 'Mauritius', '毛里求斯', 10, TRUE),
  ('PT', 'Portugal', '葡萄牙', 10, TRUE),
  
  -- 8倍速率国家
  ('UY', 'Uruguay', '乌拉圭', 8, TRUE),
  ('TR', 'Turkey', '土耳其', 8, TRUE),
  ('SK', 'Slovakia', '斯洛伐克', 8, TRUE),
  ('BY', 'Belarus', '白俄罗斯', 8, TRUE),
  ('KW', 'Kuwait', '科威特', 8, TRUE),
  ('BH', 'Bahrain', '巴林', 8, TRUE),
  ('BR', 'Brazil', '巴西', 8, TRUE),
  ('JM', 'Jamaica', '牙买加', 8, TRUE),
  ('RO', 'Romania', '罗马尼亚', 8, TRUE),
  ('HU', 'Hungary', '匈牙利', 8, TRUE),
  ('SA', 'Saudi Arabia', '沙特阿拉伯', 8, TRUE),
  ('AR', 'Argentina', '阿根廷', 8, TRUE),
  ('SG', 'Singapore', '新加坡', 8, TRUE),
  
  -- 5倍速率国家
  ('CO', 'Colombia', '哥伦比亚', 5, TRUE),
  ('QA', 'Qatar', '卡塔尔', 5, TRUE),
  ('EC', 'Ecuador', '厄瓜多尔', 5, TRUE),
  ('GQ', 'Equatorial Guinea', '赤道几内亚', 5, TRUE),
  ('TH', 'Thailand', '泰国', 5, TRUE),
  ('UA', 'Ukraine', '乌克兰', 5, TRUE),
  ('PA', 'Panama', '巴拿马', 5, TRUE),
  ('PH', 'Philippines', '菲律宾', 5, TRUE),
  ('PE', 'Peru', '秘鲁', 5, TRUE),
  ('ZA', 'South Africa', '南非', 5, TRUE),
  ('FI', 'Finland', '芬兰', 5, TRUE),
  ('TJ', 'Tajikistan', '塔吉克斯坦', 5, TRUE),
  ('HK', 'Hong Kong', '香港', 5, TRUE),
  
  -- 4倍速率国家
  ('BG', 'Bulgaria', '保加利亚', 4, TRUE),
  ('MV', 'Maldives', '马尔代夫', 4, TRUE),
  ('GR', 'Greece', '希腊', 4, TRUE),
  ('HN', 'Honduras', '洪都拉斯', 4, TRUE),
  ('KZ', 'Kazakhstan', '哈萨克斯坦', 4, TRUE),
  ('CR', 'Costa Rica', '哥斯达黎加', 4, TRUE),
  ('MZ', 'Mozambique', '莫桑比克', 4, TRUE),
  ('MY', 'Malaysia', '马来西亚', 4, TRUE),
  ('OM', 'Oman', '阿曼', 4, TRUE),
  ('RS', 'Serbia', '塞尔维亚', 4, TRUE),
  ('UZ', 'Uzbekistan', '乌兹别克斯坦', 4, TRUE),
  ('MO', 'Macao', 'Macao', 4, TRUE),
  
  -- 3倍速率国家
  ('MC', 'Monaco', '摩纳哥', 3, TRUE),
  ('BS', 'Bahamas', '巴哈马', 3, TRUE),
  ('BM', 'Bermuda', '百慕大', 3, TRUE),
  ('IM', 'Isle of Man', '马恩岛', 3, TRUE),
  ('GG', 'Guernsey', '根西岛', 3, TRUE),
  ('JE', 'Jersey', '泽西岛', 3, TRUE),
  ('BQ', 'Bonaire, Sint Eustatius', '博内尔圣尤斯特歇斯和萨巴', 3, TRUE),
  ('NC', 'New Caledonia', '新喀里多尼亚', 3, TRUE),
  ('GL', 'Greenland', '格陵兰', 3, TRUE),
  ('KM', 'Comoros', '科摩罗', 3, TRUE),
  ('KN', 'Saint Kitts and Nevis', '圣基茨和尼维斯', 3, TRUE),
  ('MQ', 'Martinique', '马提尼克岛', 3, TRUE),
  ('VI', 'Virgin Islands, U.S.', '美属维尔京群岛', 3, TRUE),
  ('CY', 'Cyprus', '塞浦路斯', 3, TRUE),
  
  -- 2倍速率国家
  ('CW', 'Curacao', '库拉索岛', 2, TRUE),
  ('GI', 'Gibraltar', '直布罗陀', 2, TRUE),
  ('GF', 'French Guiana', '法属圭亚那', 2, TRUE),
  ('YT', 'Mayotte', '马约特岛', 2, TRUE),
  ('FJ', 'Fiji', '斐济', 2, TRUE),
  ('GP', 'Guadeloupe', '瓜德罗普岛', 2, TRUE),
  ('PF', 'French Polynesia', '法属波利尼西亚', 2, TRUE),
  ('GM', 'Gambia', '冈比亚', 2, TRUE),
  ('ME', 'Montenegro', '黑山', 2, TRUE),
  ('TT', 'Trinidad and Tobago', '特立尼达和多巴哥', 2, TRUE),
  ('ST', 'Sao Tome and Principe', '圣多美和普林西比岛', 2, TRUE),
  ('RE', 'Reunion', '留尼汪', 2, TRUE),
  ('PW', 'Palau', '帕劳', 2, TRUE),
  ('GU', 'Guam', '关岛', 2, TRUE),
  ('AW', 'Aruba', '阿鲁巴', 2, TRUE),
  ('GW', 'Guinea-Bissau', '几内亚比绍', 2, TRUE),
  ('SL', 'Sierra Leone', '塞拉利昂', 2, TRUE),
  ('CV', 'Cape Verde', '佛得角', 2, TRUE),
  ('PG', 'Papua New Guinea', '巴布亚新几内亚', 2, TRUE),
  ('NA', 'Namibia', '纳米比亚', 2, TRUE),
  ('BZ', 'Belize', '伯利兹', 2, TRUE),
  ('ZW', 'Zimbabwe', '津巴布韦', 2, TRUE),
  ('AG', 'Antigua and Barbuda', '安提瓜和巴布达', 2, TRUE),
  ('MD', 'Moldova, Republic of', '摩尔多瓦共和国', 2, TRUE),
  ('CF', 'Central African Republic', '中非共和国', 2, TRUE),
  ('JO', 'Jordan', '约旦', 2, TRUE),
  ('BN', 'Brunei Darussalam', '文莱达鲁萨兰国', 2, TRUE),
  ('DJ', 'Djibouti', '吉布提', 2, TRUE),
  ('GN', 'Guinea', '几内亚', 2, TRUE),
  ('ML', 'Mali', '马里', 2, TRUE),
  ('AM', 'Armenia', '亚美尼亚', 2, TRUE),
  ('MN', 'Mongolia', '蒙古', 2, TRUE),
  ('BA', 'Bosnia and herzegovina', '波斯尼亚和黑塞哥维那', 2, TRUE),
  ('DO', 'Dominican Republic', '多米尼加共和国', 2, TRUE),
  ('SX', 'Sint Maarten (Dutch part)', '圣马丁岛（荷兰部分）', 2, TRUE),
  ('SV', 'El Salvador', '萨尔瓦多', 2, TRUE),
  ('SR', 'Suriname', '苏里南', 2, TRUE),
  ('XK', 'Kosovo', '科索沃', 2, TRUE),
  ('MR', 'Mauritania', '毛里塔尼亚', 2, TRUE),
  ('TD', 'Chad', '乍得', 2, TRUE),
  ('MK', 'Macedonia, the Former Yugoslav Republic of', '马其顿', 2, TRUE),
  ('GT', 'Guatemala', '危地马拉', 2, TRUE),
  ('AZ', 'Azerbaijan', '阿塞拜疆', 2, TRUE),
  ('LK', 'Sri Lanka', '斯里兰卡', 2, TRUE),
  ('LB', 'Lebanon', '黎巴嫩', 2, TRUE),
  ('BO', 'Bolivia', '玻利维亚', 2, TRUE),
  ('MM', 'Myanmar', '缅甸', 2, TRUE),
  ('VN', 'Viet Nam', '越南', 2, TRUE),
  ('MA', 'Morocco', '摩洛哥', 2, TRUE),
  ('GH', 'Ghana', '加纳', 2, TRUE),
  ('GY', 'Guyana', '圭亚那', 2, TRUE),
  ('ZM', 'Zambia', '赞比亚', 2, TRUE),
  ('PY', 'Paraguay', '巴拉圭', 2, TRUE),
  ('EG', 'Egypt', '埃及', 2, TRUE),
  ('CM', 'Cameroon', '喀麦隆', 2, TRUE),
  ('AO', 'Angola', '安哥拉', 2, TRUE),
  ('KE', 'Kenya', '肯尼亚', 2, TRUE),
  ('TZ', 'Tanzania, United Republic of', '坦桑尼亚联合共和国', 2, TRUE),
  ('BW', 'Botswana', '博茨瓦纳', 2, TRUE),
  ('NG', 'Nigeria', '尼日利亚', 2, TRUE),
  ('ID', 'Indonesia', '印度尼西亚', 2, TRUE),
  ('GE', 'Georgia', '格鲁吉亚', 2, TRUE),
  ('RU', 'Russian Federation', '俄罗斯联邦', 2, TRUE),
  ('NI', 'Nicaragua', '尼加拉瓜', 2, TRUE),
  ('SS', 'South Sudan', '南苏丹', 2, TRUE),
  ('LR', 'Liberia', '利比里亚', 2, TRUE),
  ('VC', 'Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', 2, TRUE),
  ('KH', 'Cambodia', '柬埔寨', 2, TRUE),
  ('PS', 'Palestinian Territory, Occupied', '巴勒斯坦领土占领土', 2, TRUE),
  ('GA', 'Gabon', '加蓬', 2, TRUE),
  
  -- 1倍速率国家
  ('TC', 'Turks and Caicos Islands', '特克斯和凯科斯群岛', 1, TRUE),
  ('LI', 'Liechtenstein', '列支敦士登', 1, TRUE),
  ('MT', 'Malta', '马耳他', 1, TRUE),
  ('KI', 'Kiribati', '基里巴斯', 1, TRUE),
  ('MP', 'Northern Mariana Islands', '北马里亚纳群岛', 1, TRUE),
  ('GD', 'Grenada', '格林纳达', 1, TRUE),
  ('CK', 'Cook Islands', '库克群岛', 1, TRUE),
  ('VG', 'Virgin Islands, British', '英属维尔京群岛', 1, TRUE),
  ('AS', 'American Samoa', '美属萨摩亚', 1, TRUE),
  ('KY', 'Cayman Islands', '开曼群岛', 1, TRUE),
  ('BB', 'Barbados', '巴巴多斯', 1, TRUE),
  ('SB', 'Solomon Islands', '所罗门群岛', 1, TRUE),
  ('WS', 'Samoa', '萨摩亚', 1, TRUE),
  ('SC', 'Seychelles', '塞舌尔', 1, TRUE),
  ('UG', 'Uganda', '乌干达', 1, TRUE),
  ('SN', 'Senegal', '塞内加尔', 1, TRUE),
  ('AL', 'Albania', '阿尔巴尼亚', 1, TRUE),
  ('AD', 'Andorra', '安道尔', 1, TRUE),
  ('YE', 'Yemen', '也门', 1, TRUE),
  ('TM', 'Turkmenistan', '土库曼斯坦', 1, TRUE),
  ('BD', 'Bangladesh', '孟加拉国', 1, TRUE),
  ('SZ', 'Swaziland', '斯威士兰', 1, TRUE),
  ('IN', 'India', '印度', 1, TRUE),
  ('CI', 'Cote D\' Ivoire', '科特迪瓦', 1, TRUE),
  ('TG', 'Togo', '多哥', 1, TRUE),
  ('HT', 'Haiti', '海地', 1, TRUE),
  ('IQ', 'Iraq', '伊拉克', 1, TRUE),
  ('CN', 'China', '中国', 1, TRUE),
  ('DZ', 'Algeria', '阿尔及利亚', 1, TRUE),
  ('BF', 'Burkina Faso', '布基纳法索', 1, TRUE),
  ('MW', 'Malawi', '马拉维', 1, TRUE),
  ('TN', 'Tunisia', '突尼斯', 1, TRUE),
  ('CD', 'Congo, the Democratic Republic of the', '刚果民主共和国', 1, TRUE),
  ('MG', 'Madagascar', '马达加斯加', 1, TRUE),
  ('PK', 'Pakistan', '巴基斯坦', 1, TRUE),
  ('BJ', 'Benin', '贝宁', 1, TRUE),
  ('LY', 'Libyan Arab Jamahiriya', '利比亚', 1, TRUE),
  ('VE', 'Venezuela', '委内瑞拉', 1, TRUE),
  ('LC', 'Saint Lucia', '圣卢西亚', 1, TRUE),
  ('NE', 'Niger', '尼日尔', 1, TRUE),
  ('ET', 'Ethiopia', '埃塞俄比亚', 1, TRUE),
  ('SO', 'Somalia', '索马里', 1, TRUE),
  ('SD', 'Sudan', '苏丹', 1, TRUE),
  ('CG', 'Congo', '刚果', 1, TRUE),
  ('LA', 'Lao People\'s Democractic Republic', '老挝人民民主共和国', 1, TRUE),
  ('BI', 'Burundi', '布隆迪', 1, TRUE),
  ('MF', 'Saint Martin (French part)', '圣马丁（法语部分）', 1, TRUE),
  ('RW', 'Rwanda', '卢旺达', 1, TRUE),
  ('AF', 'Afghanistan', '阿富汗', 1, TRUE),
  ('LS', 'Lesotho', '莱索托', 1, TRUE),
  ('BT', 'Bhutan', '不丹', 1, TRUE),
  ('NP', 'Nepal', '尼泊尔', 1, TRUE),
  ('TL', 'Timor-Leste', '东帝汶', 1, TRUE)

ON DUPLICATE KEY UPDATE
  country_name = VALUES(country_name),
  country_name_cn = VALUES(country_name_cn),
  mining_multiplier = VALUES(mining_multiplier),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

-- 验证数据
SELECT 
  COUNT(*) as total_countries,
  COUNT(DISTINCT mining_multiplier) as multiplier_levels,
  MIN(mining_multiplier) as min_multiplier,
  MAX(mining_multiplier) as max_multiplier,
  ROUND(AVG(mining_multiplier), 2) as avg_multiplier
FROM country_mining_config
WHERE is_active = TRUE;

-- 按倍率分组统计
SELECT 
  mining_multiplier,
  COUNT(*) as country_count
FROM country_mining_config
WHERE is_active = TRUE
GROUP BY mining_multiplier
ORDER BY mining_multiplier DESC;
